openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Identity'
  description: 'Project Identity with node.js & mysql'
  contact:
    email: 'ehilel@makor-capital.com'
servers:
  - url: 'http://localhost:8000'
    description: 'LOCAL server'
tags:
  - name: 'identity'
paths:
  /identity:
    get:
      tags:
        - 'identity'
      summary: 'Finds all identities'
      description: 'get all identities'
      operationId: 'getIdentities'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/identity'
        '400':
          description: 'Bad Request'
        '404':
          description: 'Not Found'
        '500':
          description: 'Internal Server Error'
  /identity/{id}:
    get:
      tags:
        - 'identity'
      summary: 'Find identity by ID'
      description: 'Returns a single identity'
      operationId: 'getIdentityById'
      parameters:
        - in: path
          name: id
          description: The identity id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/identity'
        '400':
          description: 'Bad Request'
        '404':
          description: 'Not Found'
        '500':
          description: 'Internal Server Error'
    put:
      tags:
        - 'identity'
      summary: 'Update an existing identity'
      operationId: 'updateIdentity'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Id of identity'
          required: true
          schema:
            type: string
      requestBody:
        description: insert identity content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/identity_update'
      responses:
        '200':
          description: 'Successful operation'
        '400':
          description: 'Bad Request'
        '404':
          description: 'Not Found'
        '500':
          description: 'Internal Server Error'
    delete:
      tags:
        - 'identity'
      summary: 'Delete a identity'
      operationId: 'deleteIdentity'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'identity id to delete'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: 'Successful operation'
        '400':
          description: 'Bad Request'
        '404':
          description: 'Not Found'
        '500':
          description: 'Internal Server Error'
components:
  schemas:
    identity:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        gender:
          type: string
        ip_address:
          type: string
    identity_update:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        gender:
          type: string
        ip_address:
          type: string
